# Generated by Django 5.0.7 on 2024-08-05 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bank_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bank_deposit_type', models.CharField(max_length=100)),
                ('bank_deposit_start_date', models.DateField(blank=True, null=True)),
                ('bank_deposit_end_date', models.DateField(blank=True, null=True)),
                ('stocks', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stocks_type', models.CharField(max_length=100)),
                ('stocks_start_date', models.DateField(blank=True, null=True)),
                ('stocks_end_date', models.DateField(blank=True, null=True)),
                ('bonds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonds_type', models.CharField(max_length=100)),
                ('bonds_start_date', models.DateField(blank=True, null=True)),
                ('bonds_end_date', models.DateField(blank=True, null=True)),
                ('real_estate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('real_estate_type', models.CharField(max_length=100)),
                ('real_estate_start_date', models.DateField(blank=True, null=True)),
                ('real_estate_end_date', models.DateField(blank=True, null=True)),
                ('mutual_funds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mutual_funds_type', models.CharField(max_length=100)),
                ('mutual_funds_start_date', models.DateField(blank=True, null=True)),
                ('mutual_funds_end_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
