# Generated by Django 5.0.7 on 2024-08-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investments',
            old_name='total_income',
            new_name='total_actives',
        ),
        migrations.AddField(
            model_name='investments',
            name='total_margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='bank_deposit_type',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='bonds_type',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='mutual_funds_type',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='real_estate_type',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='stocks_type',
            field=models.BooleanField(default=True),
        ),
    ]
