# Generated by Django 5.0.7 on 2024-08-18 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userbudget_userinputdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailyFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('daily_total_income', models.JSONField(default=dict)),
                ('daily_one_time_earnings', models.JSONField(default=dict)),
                ('daily_additional_income', models.JSONField(default=dict)),
                ('daily_total_invest', models.JSONField(default=dict)),
                ('daily_total_actives', models.JSONField(default=dict)),
                ('daily_total_margin', models.JSONField(default=dict)),
                ('daily_total_expenses', models.JSONField(default=dict)),
                ('daily_total_once_expenses', models.JSONField(default=dict)),
                ('daily_total_additional', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
