# Generated by Django 5.0.7 on 2024-08-12 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_expences', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('base_expences', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('base_expences_description', models.CharField(max_length=100)),
                ('base_expences_start_date', models.DateField(blank=True, null=True)),
                ('base_expences_end_date', models.DateField(blank=True, null=True)),
                ('investment_expences', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_expences', models.JSONField(blank=True, null=True)),
                ('one_time_expences', models.JSONField(blank=True, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
